"""payout_sanity — thin wrap over ``plugins.rackup_coach.abilities.payout_sanity``.

Generated by scripts/deep_promote_wire.py — no second copy of plugin logic.
"""

from __future__ import annotations

from typing import Any

from ._player import player_from_context

ABILITY = {
    "id": "payout_sanity",
    "name": "payout_sanity",
    "type": "ability",
    "status": "CODE",
    "source": "plugins.rackup_coach.abilities.payout_sanity",
    "dest": "abilities/rackup/payout_sanity.py",
    "capabilities": ["payout_sanity", "rackup"],
    "secrets_policy": "none — no wallet/key promotion",
}


def run(
    input: str = "",
    context: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    from plugins.rackup_coach.abilities import payout_sanity as _mod

    ctx = dict(context or {})
    ctx.update(kwargs)
    payload = dict(ctx.get("payload") or {})
    if input and "note" not in payload:
        payload["note"] = input
    player = player_from_context(ctx)
    result = _mod.run(player, payload)
    return {
        "ok": True,
        "ability": "payout_sanity",
        "source": ABILITY["source"],
        "result": result,
    }
