"""Learned ability bridge for `effective_engine_main` — wraps plugins.effective_engine_main_learned.invoke.

Generated by POST /v1/learn/wire. Never copies foreign source.
Status: PARTIAL (learned).
"""
from __future__ import annotations

from typing import Any


def run(payload: dict[str, Any] | None = None, context: dict[str, Any] | None = None) -> dict[str, Any]:
    payload = payload or {}
    context = context or {}
    try:
        from realai.plugins.effective_engine_main_learned import invoke
    except Exception as exc:
        return {"ok": False, "error": f"import_failed: {exc}", "learned": True, "status": "PARTIAL"}
    data = dict(payload)
    data.setdefault("ability", "effective_engine_main_leads")
    data.setdefault("input", payload.get("input") or payload.get("task") or "")
    try:
        out = invoke(data)
    except Exception as exc:
        return {"ok": False, "error": str(exc), "learned": True, "status": "PARTIAL"}
    if isinstance(out, dict):
        out.setdefault("learned", True)
        out.setdefault("status", "PARTIAL")
        out.setdefault("wired_from", "effective_engine_main")
        return out
    return {"ok": True, "result": out, "learned": True, "status": "PARTIAL", "wired_from": "effective_engine_main"}


# Alias used by some ability loaders
def execute(payload: dict[str, Any] | None = None, context: dict[str, Any] | None = None) -> dict[str, Any]:
    return run(payload, context)
