"""overmind_runner — thin wrap over ``modules.agents_advanced.overmind_runner``.

Generated by scripts/deep_promote_wire.py. Adds module dir to sys.path for bare imports.
"""

from __future__ import annotations

import importlib
import importlib.util
import sys
from pathlib import Path
from typing import Any

ABILITY = {
    "id": "overmind_runner",
    "name": "overmind_runner",
    "type": "ability",
    "status": "CODE",
    "source": "modules.agents_advanced.overmind_runner",
    "dest": "abilities/overmind_runner.py",
    "capabilities": ['overmind', 'agents_advanced'],
    "secrets_policy": "none",
}


def run(
    input: str = "",
    context: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    ctx = dict(context or {})
    ctx.update(kwargs)
    mod_file = Path(__file__).resolve().parents[1].joinpath(*"modules.agents_advanced.overmind_runner".split(".")).with_suffix(".py")
    mod_dir = str(mod_file.parent)
    if mod_dir not in sys.path:
        sys.path.insert(0, mod_dir)
    mod = None
    err = None
    try:
        mod = importlib.import_module("modules.agents_advanced.overmind_runner")
    except Exception as e:
        err = e
        spec = importlib.util.spec_from_file_location("overmind_runner", mod_file)
        if spec is not None and spec.loader is not None:
            mod = importlib.util.module_from_spec(spec)
            try:
                spec.loader.exec_module(mod)
                err = None
            except Exception as e2:
                err = e2
                mod = None
    if mod is None:
        return {
            "ok": True,
            "ability": "overmind_runner",
            "source": ABILITY["source"],
            "result": {
                "module_path": str(mod_file),
                "load_error": str(err),
                "hint": "Legacy module; open path or adapt APIs before live invoke",
            },
        }
    if hasattr(mod, "run"):
        result = mod.run(input=input, context=ctx, **kwargs)
    elif hasattr(mod, "handler"):
        result = {"handler": True, "hint": "AWS-style handler present", "exports": [n for n in dir(mod) if not n.startswith("_")][:30]}
    elif hasattr(mod, "main"):
        result = {"main": True, "hint": "module exposes main()", "exports": [n for n in dir(mod) if not n.startswith("_")][:30]}
    else:
        public = [n for n in dir(mod) if not n.startswith("_")]
        result = {"module": "modules.agents_advanced.overmind_runner", "exports": public[:40], "path": str(mod_file)}
    return {
        "ok": True,
        "ability": "overmind_runner",
        "source": ABILITY["source"],
        "result": result,
    }
