"""
RealAI-gold — RealAI living plugin (learned stub)
=============================================
Plugin id: ``realai-gold-coach``
Package:   ``plugins.realai_gold_coach``

Generated by ``python -m realai.learn_git`` (no heal / no GPU).
Same envelope as rackup-coach / atomicfizz-coach.
"""
from __future__ import annotations

from typing import Any, Optional

from .abilities import run_ability

# REALAI_LEARNED_STUB

__all__ = [
    "METADATA",
    "PLUGIN_ID",
    "invoke",
    "register",
]

PLUGIN_ID = "realai-gold-coach"
PLUGIN_VERSION = "0.1.0"

METADATA = {'name': 'realai-gold-coach', 'version': '0.1.0', 'stub': True, 'learned': True, 'capabilities': ['health', 'repo_map', 'abilities_bridge', 'agents_bridge', 'packages_bridge', 'modules_bridge', 'plugins_bridge', 'route_v1_audio_transcriptions', 'route_v1_audio_speech', 'route_v1_chat_completions', 'route_v1_embeddings', 'route_healthz', 'route_readyz', 'route_v1_models', 'route_v1_models_reload'], 'methods': ['invoke', 'health', 'repo_map', 'abilities_bridge', 'agents_bridge', 'packages_bridge', 'modules_bridge', 'plugins_bridge', 'route_v1_audio_transcriptions', 'route_v1_audio_speech', 'route_v1_chat_completions', 'route_v1_embeddings', 'route_healthz', 'route_readyz', 'route_v1_models', 'route_v1_models_reload'], 'money': {'owns_ledger': False, 'authorize_payout': False, 'moves_money': False}, 'http': {'canonical': '/v1/plugins/realai-gold-coach', 'alias': '/v1/learned/realai_gold_coach'}, 'source_slug': 'realai_gold'}


def _as_player(player: Any) -> dict[str, Any]:
    if player is None:
        return {}
    if isinstance(player, dict):
        return player
    to_dict = getattr(player, "to_dict", None)
    if callable(to_dict):
        out = to_dict()
        return out if isinstance(out, dict) else {"player": out}
    return {"value": player}


def _envelope(
    *,
    ok: bool,
    ability: str,
    result: dict[str, Any],
    error: Optional[str] = None,
) -> dict[str, Any]:
    return {
        "ok": ok,
        "plugin": PLUGIN_ID,
        "ability": ability,
        "result": result,
        "error": error,
    }


def invoke(
    ability: str | dict[str, Any] | None = None,
    player: dict[str, Any] | None = None,
    payload: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    """Dispatch an ability (atomicfizz / rackup envelope)."""
    if isinstance(ability, dict):
        data = dict(ability)
        ability_name = str(
            data.get("ability") or data.get("action") or kwargs.get("ability") or "health"
        )
        player_data = _as_player(data.get("player") or data.get("profile") or player)
        payload_data = dict(data.get("payload") or data.get("data") or payload or {})
        skip = {
            "ability",
            "action",
            "player",
            "profile",
            "payload",
            "data",
            "goal",
            "organs_enabled",
        }
        for key, value in data.items():
            if key in skip or value is None or key in payload_data:
                continue
            payload_data[key] = value
    else:
        ability_name = str(ability or kwargs.get("ability") or "health")
        player_data = _as_player(player if player is not None else kwargs.get("player"))
        payload_data = dict(payload or kwargs.get("payload") or {})

    ability_name = ability_name.strip() or "health"
    result = run_ability(ability_name, player_data, payload_data)
    if isinstance(result, dict) and result.get("error"):
        return _envelope(
            ok=False,
            ability=ability_name,
            result=result,
            error=str(result.get("error")),
        )
    return _envelope(
        ok=True,
        ability=ability_name,
        result=result if isinstance(result, dict) else {"value": result},
        error=None,
    )


def register(model=None, config=None) -> dict[str, Any]:
    """Register plugin methods on a RealAI model instance (sample_plugin style)."""
    config = config or {}

    def _invoke(data=None):
        return invoke(data)

    if model is not None:
        setattr(model, "realai_gold_coach", _invoke)
        setattr(model, "realai_gold_coach", _invoke)

    meta = dict(METADATA)
    meta["config"] = config
    meta["ok"] = True
    return meta
