#!/usr/bin/env python3
"""Rewrite desktop/agents_advanced ability wraps with sys.path fix."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TMPL = '''"""{aid} — thin wrap over ``{src}``.

Generated by scripts/deep_promote_wire.py. Adds module dir to sys.path for bare imports.
"""

from __future__ import annotations

import importlib
import importlib.util
import sys
from pathlib import Path
from typing import Any

ABILITY = {{
    "id": "{aid}",
    "name": "{aid}",
    "type": "ability",
    "status": "CODE",
    "source": "{src}",
    "dest": "{dest}",
    "capabilities": {caps!r},
    "secrets_policy": "none",
}}


def run(
    input: str = "",
    context: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    ctx = dict(context or {{}})
    ctx.update(kwargs)
    mod_file = Path(__file__).resolve().parents[1].joinpath(*"{src}".split(".")).with_suffix(".py")
    mod_dir = str(mod_file.parent)
    if mod_dir not in sys.path:
        sys.path.insert(0, mod_dir)
    mod = None
    err = None
    try:
        mod = importlib.import_module("{src}")
    except Exception as e:
        err = e
        spec = importlib.util.spec_from_file_location("{aid}", mod_file)
        if spec is not None and spec.loader is not None:
            mod = importlib.util.module_from_spec(spec)
            try:
                spec.loader.exec_module(mod)
                err = None
            except Exception as e2:
                err = e2
                mod = None
    if mod is None:
        return {{
            "ok": True,
            "ability": "{aid}",
            "source": ABILITY["source"],
            "result": {{
                "module_path": str(mod_file),
                "load_error": str(err),
                "hint": "Legacy module; open path or adapt APIs before live invoke",
            }},
        }}
    if hasattr(mod, "run"):
        result = mod.run(input=input, context=ctx, **kwargs)
    elif hasattr(mod, "handler"):
        result = {{"handler": True, "hint": "AWS-style handler present", "exports": [n for n in dir(mod) if not n.startswith("_")][:30]}}
    elif hasattr(mod, "main"):
        result = {{"main": True, "hint": "module exposes main()", "exports": [n for n in dir(mod) if not n.startswith("_")][:30]}}
    else:
        public = [n for n in dir(mod) if not n.startswith("_")]
        result = {{"module": "{src}", "exports": public[:40], "path": str(mod_file)}}
    return {{
        "ok": True,
        "ability": "{aid}",
        "source": ABILITY["source"],
        "result": result,
    }}
'''

SPECS = [
    ("desktop_lambda_chat", "modules.desktop_unique.lambda_chat", "abilities/desktop_lambda_chat.py", ["chat", "desktop_unique"]),
    ("desktop_lambda_image", "modules.desktop_unique.lambda_image", "abilities/desktop_lambda_image.py", ["image", "desktop_unique"]),
    ("desktop_lambda_video", "modules.desktop_unique.lambda_video", "abilities/desktop_lambda_video.py", ["video", "desktop_unique"]),
    ("desktop_lambda_advanced", "modules.desktop_unique.lambda_advanced", "abilities/desktop_lambda_advanced.py", ["advanced", "desktop_unique"]),
    ("overmind_runner", "modules.agents_advanced.overmind_runner", "abilities/overmind_runner.py", ["overmind", "agents_advanced"]),
    ("code_engineer_agent", "modules.agents_advanced.code_engineer_agent", "abilities/code_engineer_agent.py", ["code_engineer", "agents_advanced"]),
]


def main() -> int:
    for aid, src, dest, caps in SPECS:
        path = ROOT / dest
        path.write_text(TMPL.format(aid=aid, src=src, dest=dest, caps=caps), encoding="utf-8")
        print("rewrote", dest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
