"""Scaffold / upgrade a learned coach plugin stub (atomicfizz_coach pattern)."""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# Never overwrite these live product plugins.
PROTECTED_PLUGIN_PACKAGES = frozenset(
    {
        "rackup_coach",
        "rackup-coach",
        "atomicfizz_coach",
        "atomic_fizz_realai",
        "desktop_plugins",
        "agent_tools",
        "abilities",
        "core",
        "plugins",
        "tools",
    }
)

STUB_MARK = "REALAI_LEARNED_STUB"

def _fill(template: str, **tokens: str) -> str:
    out = template
    for key, value in tokens.items():
        out = out.replace("@@" + key + "@@", value)
    return out


_INIT_TEMPLATE = '''\
"""
@@TITLE@@ — RealAI living plugin (learned stub)
=============================================
Plugin id: ``@@PLUGIN_ID@@``
Package:   ``plugins.@@PACKAGE@@``

Generated by ``python -m realai.learn_git`` (no heal / no GPU).
Same envelope as rackup-coach / atomicfizz-coach.
"""
from __future__ import annotations

from typing import Any, Optional

from .abilities import run_ability

# @@MARK@@

__all__ = [
    "METADATA",
    "PLUGIN_ID",
    "invoke",
    "register",
]

PLUGIN_ID = "@@PLUGIN_ID@@"
PLUGIN_VERSION = "@@VERSION@@"

METADATA = @@METADATA_REPR@@


def _as_player(player: Any) -> dict[str, Any]:
    if player is None:
        return {}
    if isinstance(player, dict):
        return player
    to_dict = getattr(player, "to_dict", None)
    if callable(to_dict):
        out = to_dict()
        return out if isinstance(out, dict) else {"player": out}
    return {"value": player}


def _envelope(
    *,
    ok: bool,
    ability: str,
    result: dict[str, Any],
    error: Optional[str] = None,
) -> dict[str, Any]:
    return {
        "ok": ok,
        "plugin": PLUGIN_ID,
        "ability": ability,
        "result": result,
        "error": error,
    }


def invoke(
    ability: str | dict[str, Any] | None = None,
    player: dict[str, Any] | None = None,
    payload: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    """Dispatch an ability (atomicfizz / rackup envelope)."""
    if isinstance(ability, dict):
        data = dict(ability)
        ability_name = str(
            data.get("ability") or data.get("action") or kwargs.get("ability") or "health"
        )
        player_data = _as_player(data.get("player") or data.get("profile") or player)
        payload_data = dict(data.get("payload") or data.get("data") or payload or {})
        skip = {
            "ability",
            "action",
            "player",
            "profile",
            "payload",
            "data",
            "goal",
            "organs_enabled",
        }
        for key, value in data.items():
            if key in skip or value is None or key in payload_data:
                continue
            payload_data[key] = value
    else:
        ability_name = str(ability or kwargs.get("ability") or "health")
        player_data = _as_player(player if player is not None else kwargs.get("player"))
        payload_data = dict(payload or kwargs.get("payload") or {})

    ability_name = ability_name.strip() or "health"
    result = run_ability(ability_name, player_data, payload_data)
    if isinstance(result, dict) and result.get("error"):
        return _envelope(
            ok=False,
            ability=ability_name,
            result=result,
            error=str(result.get("error")),
        )
    return _envelope(
        ok=True,
        ability=ability_name,
        result=result if isinstance(result, dict) else {"value": result},
        error=None,
    )


def register(model=None, config=None) -> dict[str, Any]:
    """Register plugin methods on a RealAI model instance (sample_plugin style)."""
    config = config or {}

    def _invoke(data=None):
        return invoke(data)

    if model is not None:
        setattr(model, "@@PACKAGE@@", _invoke)
        setattr(model, "@@SAFE_ATTR@@_coach", _invoke)

    meta = dict(METADATA)
    meta["config"] = config
    meta["ok"] = True
    return meta
'''

_ABILITIES_INIT = '''\
"""Learned coach stub ability modules (auto-discover *.py)."""
from __future__ import annotations

import importlib
from pathlib import Path
from typing import Any, Callable

# REALAI_LEARNED_STUB

ABILITY_RUNNERS: dict[str, Callable[[dict[str, Any], dict[str, Any]], dict[str, Any]]] = {}


def _load() -> None:
    here = Path(__file__).resolve().parent
    pkg = __package__ or ""
    for path in sorted(here.glob("*.py")):
        if path.name.startswith("_"):
            continue
        mod = importlib.import_module(f".{path.stem}", pkg)
        run = getattr(mod, "run", None)
        if not callable(run):
            continue
        ABILITY_RUNNERS[path.stem] = run
        for alias in getattr(mod, "ALIASES", ()) or ():
            ABILITY_RUNNERS[str(alias)] = run
    if "health" in ABILITY_RUNNERS:
        ABILITY_RUNNERS.setdefault("ping", ABILITY_RUNNERS["health"])


_load()


def run_ability(
    name: str,
    player: dict[str, Any] | None = None,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    key = (name or "health").strip().lower()
    fn = ABILITY_RUNNERS.get(key)
    if not fn:
        return {
            "error": f"unknown ability '{name}'",
            "available": sorted(set(ABILITY_RUNNERS)),
        }
    return fn(player or {}, payload or {})


__all__ = ["ABILITY_RUNNERS", "run_ability"]
'''

_ABILITY_STUB = '''\
"""Stub ability `@@ABILITY_ID@@` — learned from git-learn (no runtime heal)."""
from __future__ import annotations

from typing import Any

# REALAI_LEARNED_STUB

PLUGIN_ID = "@@PLUGIN_ID@@"
PLUGIN_VERSION = "@@VERSION@@"
ABILITY_ID = "@@ABILITY_ID@@"
ALIASES = @@ALIASES_REPR@@


def run(player: dict[str, Any], payload: dict[str, Any] | None = None) -> dict[str, Any]:
    payload = payload or {}
    return {
        "status": "ok",
        "plugin": PLUGIN_ID,
        "ability": ABILITY_ID,
        "version": PLUGIN_VERSION,
        "stub": True,
        "learned": True,
        "heal": False,
        "description": @@DESC_REPR@@,
        "player_id": (player or {}).get("player_id") or (player or {}).get("id") or "",
        "notes": "Placeholder learned ability — contract discovery only; no runtime heal.",
        "echo": {
            "payload_keys": sorted(str(k) for k in payload.keys()),
        },
    }
'''


def plugin_package_name(slug: str) -> str:
    base = re.sub(r"[^a-z0-9_]+", "_", (slug or "repo").lower()).strip("_") or "repo"
    if base.endswith("_coach"):
        pkg = base
    else:
        pkg = f"{base}_coach"
    if pkg in PROTECTED_PLUGIN_PACKAGES or pkg.replace("_", "-") in PROTECTED_PLUGIN_PACKAGES:
        pkg = f"{base}_learned_coach"
    return pkg


def plugin_id_for(package: str) -> str:
    return package.replace("_", "-")


def _ability_id(raw: str) -> str:
    s = re.sub(r"[^a-z0-9_]+", "_", (raw or "").lower()).strip("_")
    return s or "ability"


def _existing_ability_ids(abilities_dir: Path) -> list[str]:
    if not abilities_dir.is_dir():
        return []
    return sorted(
        p.stem
        for p in abilities_dir.glob("*.py")
        if p.name != "__init__.py" and not p.name.startswith("_")
    )


def _is_generated(path: Path) -> bool:
    if not path.is_file():
        return True
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    return STUB_MARK in text


def _bump_patch(version: str) -> str:
    parts = (version or "0.1.0").split(".")
    while len(parts) < 3:
        parts.append("0")
    try:
        parts[2] = str(int(parts[2]) + 1)
    except ValueError:
        parts[2] = "1"
    return ".".join(parts[:3])


def _read_state(plugin_dir: Path) -> dict[str, Any]:
    state_path = plugin_dir / ".learned.json"
    if not state_path.is_file():
        return {}
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def _write_state(plugin_dir: Path, state: dict[str, Any]) -> None:
    (plugin_dir / ".learned.json").write_text(
        json.dumps(state, indent=2) + "\n", encoding="utf-8"
    )


def _manifest_yaml(
    *,
    plugin_id: str,
    package: str,
    version: str,
    title: str,
    description: str,
    abilities: list[dict[str, str]],
) -> str:
    lines = [
        f"# RealAI living plugin — {title} (learned stub)",
        "# Provider-level AI capability only. Generated by git-learn. No heal.",
        "",
        f"name: {plugin_id}",
        f"version: {version}",
        "author: RealAI / git-learn",
        "description: >",
        f"  {description.replace(chr(10), ' ')[:240] or 'Learned coach stub from a foreign git tree.'}",
        "",
        "kind: living_plugin",
        "provider_level: true",
        "homepage: https://github.com/Unwrenchable/RealAi",
        "stub: true",
        "learned: true",
        "",
        "permissions:",
        "  - none",
        "",
        "entrypoints:",
        f"  register: plugins.{package}:register",
        f"  invoke: plugins.{package}:invoke",
        "",
        "capabilities:",
    ]
    for ab in abilities:
        lines.append(f"  - {ab['id']}")
    lines += [
        "",
        "money:",
        "  authorize_payout: false",
        "  owns_ledger: false",
        "  moves_money: false",
        "",
        "abilities:",
    ]
    for ab in abilities:
        lines.append(f"  - id: {ab['id']}")
        lines.append(f"    module: abilities.{ab['id']}")
        desc = (ab.get("description") or "Learned stub").replace("\n", " ")[:160]
        lines.append(f"    description: {desc}")
    lines += [
        "",
        "config_defaults:",
        "  stub: true",
        "  learned: true",
        "  organs_enabled: false",
        "  authorize_payout: false",
        "",
    ]
    return "\n".join(lines)


def _readme(*, plugin_id: str, package: str, version: str, abilities: list[dict[str, str]], title: str) -> str:
    rows = "\n".join(f"| `{a['id']}` | {a.get('description') or 'stub'} |" for a in abilities)
    return f"""# {title} (`{plugin_id}`)

Learned **living** RealAI plugin stub — same provider boundary as
`rackup-coach` / `atomicfizz-coach`. Generated by `python -m realai.learn_git`.

| | |
|--|--|
| Plugin id | `{plugin_id}` |
| Package | `plugins.{package}` |
| Folder | `realai/plugins/{package}` |
| Version | `{version}` (learned stub) |

This is **not** a runtime heal. Abilities return structured placeholders.

## Abilities (placeholders)

| Ability | Description |
|---------|-------------|
{rows}

Canonical HTTP: `POST {{REALAI_BASE_URL}}/v1/plugins/{plugin_id}`
"""


def merge_abilities(
    proposed: list[dict[str, Any]],
    existing_ids: list[str],
) -> list[dict[str, str]]:
    merged: list[dict[str, str]] = []
    seen: set[str] = set()

    def add(aid: str, desc: str) -> None:
        key = _ability_id(aid)
        if not key or key in seen:
            return
        seen.add(key)
        merged.append({"id": key, "description": desc or f"Stub ability {key}"})

    add("health", "Stub liveness / contract discovery (no runtime heal)")
    for item in proposed or []:
        if isinstance(item, dict):
            add(str(item.get("id") or ""), str(item.get("description") or ""))
        elif isinstance(item, str):
            add(item, f"Stub ability {item}")
    for eid in existing_ids:
        add(eid, f"Existing stub ability {eid}")
    return merged


def scaffold_plugin(
    packet: dict[str, Any],
    *,
    plugins_root: Path,
    write: bool = True,
) -> dict[str, Any]:
    slug = str(packet.get("slug") or "repo")
    package = plugin_package_name(slug)
    plugin_id = plugin_id_for(package)
    plugin_dir = plugins_root / package
    existed = plugin_dir.is_dir()
    summary = packet.get("summary") if isinstance(packet.get("summary"), dict) else {}
    title = str(summary.get("title") or package)
    description = str(summary.get("description") or f"Learned coach stub for {slug}")
    proposed = list(packet.get("proposed_abilities") or [])
    existing_ids = _existing_ability_ids(plugin_dir / "abilities")
    abilities = merge_abilities(proposed, existing_ids)

    state = _read_state(plugin_dir)
    version = str(state.get("version") or "0.1.0")
    prev_sha = str(state.get("packet_sha") or "")
    fps = packet.get("fingerprints") or []
    packet_sha = ""
    if isinstance(fps, list) and fps:
        packet_sha = str(fps[0].get("sha1") or "") + f":{len(fps)}"
    upgraded = existed
    if existed and prev_sha and prev_sha != packet_sha:
        version = _bump_patch(version)
    elif not existed:
        version = "0.1.0"

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []

    metadata = {
        "name": plugin_id,
        "version": version,
        "stub": True,
        "learned": True,
        "capabilities": [a["id"] for a in abilities],
        "methods": ["invoke"] + [a["id"] for a in abilities],
        "money": {
            "owns_ledger": False,
            "authorize_payout": False,
            "moves_money": False,
        },
        "http": {
            "canonical": f"/v1/plugins/{plugin_id}",
            "alias": f"/v1/learned/{package}",
        },
        "source_slug": slug,
    }

    proposal = {
        "id": plugin_id,
        "package": package,
        "path": str(plugin_dir),
        "version": version,
        "abilities": [a["id"] for a in abilities],
        "protected_collision": package.endswith("_learned_coach"),
    }

    if not write:
        return {
            "ok": True,
            "wrote": False,
            "upgraded": upgraded,
            "plugin_dir": str(plugin_dir),
            "plugin_proposal": proposal,
            "abilities": abilities,
        }

    plugin_dir.mkdir(parents=True, exist_ok=True)
    pkg_init = plugins_root / "__init__.py"
    if not pkg_init.exists():
        pkg_init.write_text('"""Plugins namespace (git-learn created)."""\n', encoding="utf-8")
    abilities_dir = plugin_dir / "abilities"
    abilities_dir.mkdir(parents=True, exist_ok=True)

    def _put(path: Path, content: str, *, force: bool = False) -> None:
        rel = path.relative_to(plugin_dir).as_posix()
        if path.exists() and not force and not _is_generated(path):
            skipped.append(rel)
            return
        prev = path.read_text(encoding="utf-8") if path.exists() else None
        if prev == content:
            return
        path.write_text(content, encoding="utf-8")
        if prev is None:
            created.append(rel)
        else:
            updated.append(rel)

    init_py = _fill(
        _INIT_TEMPLATE,
        TITLE=title.replace('"', "'")[:80],
        PLUGIN_ID=plugin_id,
        PACKAGE=package,
        VERSION=version,
        MARK=STUB_MARK,
        METADATA_REPR=repr(metadata),
        SAFE_ATTR=package.replace("_coach", ""),
    )
    _put(plugin_dir / "__init__.py", init_py, force=True)
    _put(plugin_dir / "manifest.yaml", _manifest_yaml(
        plugin_id=plugin_id,
        package=package,
        version=version,
        title=title,
        description=description,
        abilities=abilities,
    ), force=True)
    _put(plugin_dir / "README.md", _readme(
        plugin_id=plugin_id,
        package=package,
        version=version,
        abilities=abilities,
        title=title,
    ), force=True)
    _put(abilities_dir / "__init__.py", _ABILITIES_INIT, force=True)

    for ab in abilities:
        aid = ab["id"]
        aliases = ["ping"] if aid == "health" else []
        body = _fill(
            _ABILITY_STUB,
            ABILITY_ID=aid,
            PLUGIN_ID=plugin_id,
            VERSION=version,
            ALIASES_REPR=repr(tuple(aliases)),
            DESC_REPR=repr(ab.get("description") or ""),
        )
        dest = abilities_dir / f"{aid}.py"
        _put(dest, body, force=False)

    _write_state(
        plugin_dir,
        {
            "slug": slug,
            "package": package,
            "plugin_id": plugin_id,
            "version": version,
            "packet_sha": packet_sha,
            "abilities": [a["id"] for a in abilities],
        },
    )

    # Guard: no numbered junk copies
    junk = [
        p.name
        for p in plugin_dir.glob("*_[0-9].py")
        if p.is_file()
    ]

    return {
        "ok": True,
        "wrote": True,
        "upgraded": upgraded,
        "plugin_dir": str(plugin_dir),
        "plugin_proposal": proposal,
        "abilities": abilities,
        "created": created,
        "updated": updated,
        "skipped_custom": skipped,
        "junk_numbered": junk,
    }
