#Requires -Version 5.1
<#
.SYNOPSIS
  RealAI-clean bootstrap - prepares C:\RealAI-clean for Craft + dispatcher + self-heal.

.DESCRIPTION
  - Ensures directory layout (scripts, logs, models, recovered)
  - Creates missing placeholder phase scripts so dispatcher never hard-fails on missing files
  - Sets recommended environment variables for the current session + optionally permanent
  - Verifies Python + key packages
  - Optionally launches Craft with the master unified prompt

.NOTES
  Run from elevated or normal PowerShell:
    cd C:\RealAI-clean
    .\scripts\bootstrap_realai.ps1
    .\scripts\bootstrap_realai.ps1 -LaunchMaster
    .\scripts\bootstrap_realai.ps1 -ForcePlaceholders
#>

param(
    [switch]$LaunchMaster,
    [switch]$ForcePlaceholders,
    [switch]$PermanentEnv,
    [string]$RealAIHome = "C:\RealAI-clean"
)

$ErrorActionPreference = "Continue"
$ProgressPreference = "SilentlyContinue"

function Write-Step($msg) { Write-Host "[bootstrap] $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "[  ok    ] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[ warn   ] $msg" -ForegroundColor Yellow }
function Write-Err($msg)  { Write-Host "[ error  ] $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "=== RealAI-clean Bootstrap ===" -ForegroundColor Magenta
Write-Host "Target HOME : $RealAIHome"
Write-Host ""

# ------------------------------------------------------------------
# 1. Core directories
# ------------------------------------------------------------------
$dirs = @(
    $RealAIHome,
    "$RealAIHome\scripts",
    "$RealAIHome\logs",
    "$RealAIHome\models",
    "$RealAIHome\recovered",
    "$RealAIHome\realai",
    "$RealAIHome\realai\cli",
    "$RealAIHome\imports",
    "$RealAIHome\imports\external"
)

foreach ($d in $dirs) {
    if (-not (Test-Path $d)) {
        New-Item -ItemType Directory -Path $d -Force | Out-Null
        Write-Ok "created $d"
    } else {
        Write-Step "exists  $d"
    }
}

# ------------------------------------------------------------------
# 2. Environment (session + optional permanent)
# ------------------------------------------------------------------
$env:REALAI_HOME = $RealAIHome
$env:REALAI_WORKSPACE = (Get-Location).Path
$env:REALAI_VULKAN_DIR = if ($env:REALAI_VULKAN_DIR) { $env:REALAI_VULKAN_DIR } else { "C:\llama-vulkan" }
$env:REALAI_GPU_HOST  = "127.0.0.1"
$env:REALAI_GPU_PORT  = "8080"
$env:PYTHONUTF8 = "1"
$env:PYTHONIOENCODING = "utf-8"

Write-Ok "REALAI_HOME        = $env:REALAI_HOME"
Write-Ok "REALAI_WORKSPACE   = $env:REALAI_WORKSPACE"
Write-Ok "REALAI_VULKAN_DIR  = $env:REALAI_VULKAN_DIR"

if ($PermanentEnv) {
    [Environment]::SetEnvironmentVariable("REALAI_HOME", $RealAIHome, "User")
    [Environment]::SetEnvironmentVariable("REALAI_VULKAN_DIR", $env:REALAI_VULKAN_DIR, "User")
    Write-Ok "Permanent user env vars written (restart shells to pick up)"
}

# ------------------------------------------------------------------
# 3. Ensure the phase scripts exist (safe placeholders if missing)
# ------------------------------------------------------------------
$phaseScripts = @(
    # Original core pipeline
    "scan_repos_for_realai.py",
    "find_self_improve_and_lost.py",
    "promote_unified_realai.py",
    "world_model_merger.py",
    "plugin_registry_builder.py",
    "unified_structure_validator.py",
    "monitor_model.py",

    # Extra recovery / wiring phases (now part of full dispatch)
    "diff_imports_promote_allowlist.py",
    "curated_promote.py",
    "wire_recovered.py",
    "self_heal_loop.py",
    "heal_cli.py"
)

$placeholder = @'
#!/usr/bin/env python3
"""Placeholder phase script generated by bootstrap_realai.ps1.
Replace with the real implementation when ready.
Exits 0 so the dispatcher pipeline continues.
"""
import sys
from pathlib import Path
print(f"[placeholder] {Path(__file__).name} - no-op (replace me)")
sys.exit(0)
'@

$scriptsDir = Join-Path $RealAIHome "scripts"
foreach ($name in $phaseScripts) {
    $path = Join-Path $scriptsDir $name
    if (-not (Test-Path $path)) {
        Set-Content -Path $path -Value $placeholder -Encoding UTF8
        Write-Warn "placeholder written: $path"
    }
    elseif ($ForcePlaceholders) {
        Set-Content -Path $path -Value $placeholder -Encoding UTF8
        Write-Warn "FORCE placeholder overwritten: $path"
    }
    else {
        Write-Ok "phase script present: $name"
    }
}

# ------------------------------------------------------------------
# 4. Quick Python health
# ------------------------------------------------------------------
try {
    $py = & python -c "import sys; print(sys.executable); print(sys.version)" 2>&1
    Write-Ok "Python: $py"
} catch {
    Write-Err "python not found on PATH - install Python 3.10+ and re-run"
}

# ------------------------------------------------------------------
# 5. craft.py location check
# ------------------------------------------------------------------
$craftCandidates = @(
    "$RealAIHome\realai\cli\craft.py",
    "$RealAIHome\realai\craft.py",
    "$RealAIHome\craft.py"
)
$craftFound = $null
foreach ($c in $craftCandidates) {
    if (Test-Path $c) { $craftFound = $c; break }
}
if ($craftFound) {
    Write-Ok "craft.py found: $craftFound"
} else {
    Write-Warn "craft.py not found under expected paths - copy the fixed craft.py to:"
    Write-Warn "  $RealAIHome\realai\cli\craft.py"
}

# ------------------------------------------------------------------
# 6. Optional launch of master cycle
# ------------------------------------------------------------------
if ($LaunchMaster) {
    Write-Host ""
    Write-Step "Launching Craft with master unified prompt..."
    $master = Join-Path $scriptsDir "master_unified_prompt.txt"
    if (-not (Test-Path $master)) {
        # fallback: look next to this script or in artifacts-style location
        $master = Join-Path $PSScriptRoot "master_unified_prompt.txt"
    }
    if (Test-Path $master) {
        $prompt = Get-Content $master -Raw -Encoding UTF8
        if ($craftFound) {
            # one-shot mode
            & python $craftFound $prompt
        } else {
            Write-Err "Cannot launch - craft.py missing"
        }
    } else {
        Write-Warn "master_unified_prompt.txt not found - paste the master prompt manually into Craft"
    }
}

Write-Host ""
Write-Host "Bootstrap complete." -ForegroundColor Magenta
Write-Host "Next:  realai   (or python realai\cli\craft.py)"
Write-Host "Then:  /dispatch all     or paste the master unified prompt"
Write-Host ""
