#!/usr/bin/env python3
"""Apply thin wires from deep_promote_queue.json (scan + wire-thin policy).

- RackUp mis-homed abilities → abilities/rackup/<name>.py wraps
- modules/desktop_unique + agents_advanced → thin ability wraps when missing
- Novel orchestrator_* → modules/orchestrators/ if missing (copy once)
- Updates registry.json + v3_runtime_bridge aliases + ability_catalog entries
- Rebuilds scan_results/ability_catalog.json

Never promotes secrets. Never deletes nests. Never overwrites live modules blindly.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
QUEUE = ROOT / "scan_results" / "deep_promote_queue.json"
LOG = ROOT / "scan_results" / "DEEP_PROMOTE_WIRE_LOG.json"
REGISTRY = ROOT / "realai" / "abilities" / "registry.json"
BRIDGE = ROOT / "realai" / "v3_runtime_bridge.py"
CATALOG = ROOT / "realai" / "ability_catalog.py"

RACKUP_SKIP = {"__init__.py", "_player.py"}


def utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_queue() -> List[Dict[str, Any]]:
    if not QUEUE.is_file():
        return []
    data = json.loads(QUEUE.read_text(encoding="utf-8"))
    return list(data.get("items") or [])


def rackup_wrap_source(stem: str) -> str:
    return f'''"""{stem} — thin wrap over ``plugins.rackup_coach.abilities.{stem}``.

Generated by scripts/deep_promote_wire.py — no second copy of plugin logic.
"""

from __future__ import annotations

from typing import Any

from ._player import player_from_context

ABILITY = {{
    "id": "{stem}",
    "name": "{stem}",
    "type": "ability",
    "status": "CODE",
    "source": "plugins.rackup_coach.abilities.{stem}",
    "dest": "abilities/rackup/{stem}.py",
    "capabilities": ["{stem}", "rackup"],
    "secrets_policy": "none — no wallet/key promotion",
}}


def run(
    input: str = "",
    context: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    from plugins.rackup_coach.abilities import {stem} as _mod

    ctx = dict(context or {{}})
    ctx.update(kwargs)
    payload = dict(ctx.get("payload") or {{}})
    if input and "note" not in payload:
        payload["note"] = input
    player = player_from_context(ctx)
    result = _mod.run(player, payload)
    return {{
        "ok": True,
        "ability": "{stem}",
        "source": ABILITY["source"],
        "result": result,
    }}
'''


def module_ability_wrap(ability_id: str, source_module: str, dest_rel: str, caps: List[str]) -> str:
    return f'''"""{ability_id} — thin wrap over ``{source_module}``.

Generated by scripts/deep_promote_wire.py. Adds module dir to sys.path for bare imports.
"""

from __future__ import annotations

import importlib
import importlib.util
import sys
from pathlib import Path
from typing import Any

ABILITY = {{
    "id": "{ability_id}",
    "name": "{ability_id}",
    "type": "ability",
    "status": "CODE",
    "source": "{source_module}",
    "dest": "{dest_rel}",
    "capabilities": {caps!r},
    "secrets_policy": "none",
}}


def run(
    input: str = "",
    context: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    ctx = dict(context or {{}})
    ctx.update(kwargs)
    mod_file = Path(__file__).resolve().parents[1].joinpath(*"{source_module}".split(".")).with_suffix(".py")
    mod_dir = str(mod_file.parent)
    if mod_dir not in sys.path:
        sys.path.insert(0, mod_dir)
    mod = None
    err: Exception | None = None
    try:
        mod = importlib.import_module("{source_module}")
    except Exception as e:
        err = e
        spec = importlib.util.spec_from_file_location("{ability_id}", mod_file)
        if spec is not None and spec.loader is not None:
            mod = importlib.util.module_from_spec(spec)
            try:
                spec.loader.exec_module(mod)
                err = None
            except Exception as e2:
                err = e2
                mod = None
    if mod is None:
        return {{
            "ok": True,
            "ability": "{ability_id}",
            "source": ABILITY["source"],
            "result": {{
                "module_path": str(mod_file),
                "load_error": str(err),
                "hint": "Legacy module; open path or adapt APIs before live invoke",
            }},
        }}
    if hasattr(mod, "run"):
        result = mod.run(input=input, context=ctx, **kwargs)  # type: ignore[misc]
    elif hasattr(mod, "handler"):
        result = {{"handler": True, "exports": [n for n in dir(mod) if not n.startswith("_")][:30]}}
    elif hasattr(mod, "main"):
        result = {{"main": True, "exports": [n for n in dir(mod) if not n.startswith("_")][:30]}}
    else:
        public = [n for n in dir(mod) if not n.startswith("_")]
        result = {{"module": "{source_module}", "exports": public[:40], "path": str(mod_file)}}
    return {{
        "ok": True,
        "ability": "{ability_id}",
        "source": ABILITY["source"],
        "result": result,
    }}
'''


def ensure_rackup_init(stems: List[str]) -> None:
    init = ROOT / "abilities" / "rackup" / "__init__.py"
    # rebuild from actual files
    files = sorted(
        p.stem
        for p in (ROOT / "abilities" / "rackup").glob("*.py")
        if p.name not in RACKUP_SKIP
    )
    lines = [
        '"""RackUp domain abilities — thin surface over ``plugins.rackup_coach``."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for stem in files:
        lines.append(f"from .{stem} import ABILITY as {stem.upper()}_ABILITY")
        lines.append(f"from .{stem} import run as run_{stem}")
    lines.append("")
    lines.append(f"ABILITY_IDS = {tuple(files)!r}")
    lines.append("")
    lines.append("__all__ = [")
    lines.append('    "ABILITY_IDS",')
    for stem in files:
        lines.append(f'    "{stem.upper()}_ABILITY",')
        lines.append(f'    "run_{stem}",')
    lines.append("]")
    lines.append("")
    init.write_text("\n".join(lines), encoding="utf-8")


def patch_bridge(stems: List[str]) -> int:
    if not BRIDGE.is_file() or not stems:
        return 0
    text = BRIDGE.read_text(encoding="utf-8")
    added = 0
    for stem in stems:
        needle = f'"{stem}": "abilities.rackup.{stem}"'
        if needle in text:
            continue
        # insert before game_world line inside ability_handlers
        marker = '"game_world": "abilities.game_world",'
        if marker not in text:
            continue
        insert = f'            "{stem}": "abilities.rackup.{stem}",\n            '
        text = text.replace(marker, insert + marker, 1)
        added += 1
    if added:
        BRIDGE.write_text(text, encoding="utf-8")
    return added


def registry_upsert(entries: List[Dict[str, Any]]) -> int:
    data = {"abilities": [], "tools": [], "tasks": []}
    if REGISTRY.is_file():
        data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    existing = {a.get("id"): i for i, a in enumerate(data.get("abilities") or [])}
    added = 0
    for e in entries:
        eid = e["id"]
        if eid in existing:
            data["abilities"][existing[eid]] = e
        else:
            data.setdefault("abilities", []).append(e)
            added += 1
    REGISTRY.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return added


def catalog_ensure_block(stem: str, name: str, modules: List[str], live_path: str) -> bool:
    """Append a CODE ability block to ability_catalog.py if id missing."""
    text = CATALOG.read_text(encoding="utf-8")
    if f'"id": "{stem}"' in text:
        return False
    block = f'''    {{
        "id": "{stem}",
        "name": "{name}",
        "pillar": "advanced",
        "keywords": ["{stem.replace('_', ' ')}", "rackup", "{stem}"],
        "status": "CODE",
        "live_path": "{live_path}",
        "modules": {json.dumps(modules)},
    }},
'''
    # insert before plugin_system or memory_learning
    for marker in ('    {\n        "id": "plugin_system"', '    {\n        "id": "memory_learning"'):
        if marker in text:
            text = text.replace(marker, block + marker, 1)
            CATALOG.write_text(text, encoding="utf-8")
            return True
    # fallback: before TECH_ABILITY_SEED closing — find last ability in list is fragile; append near coach
    marker = '    {\n        "id": "coach"'
    if marker in text:
        # insert after rating_update block end is hard; put before coach
        text = text.replace(marker, block + marker, 1)
        CATALOG.write_text(text, encoding="utf-8")
        return True
    return False


def wire_rackup(dry_run: bool, limit: int) -> List[Dict[str, Any]]:
    actions = []
    ab_dir = ROOT / "plugins" / "rackup_coach" / "abilities"
    if not ab_dir.is_dir():
        return actions
    stems: List[str] = []
    for p in sorted(ab_dir.glob("*.py")):
        if p.name in RACKUP_SKIP or p.name == "__init__.py":
            continue
        dest = ROOT / "abilities" / "rackup" / p.name
        if dest.is_file():
            continue
        stem = p.stem
        stems.append(stem)
        rec = {"id": stem, "action": "thin_wrap", "dest": str(dest.relative_to(ROOT))}
        if dry_run:
            rec["status"] = "would_write"
            actions.append(rec)
            continue
        dest.write_text(rackup_wrap_source(stem), encoding="utf-8")
        rec["status"] = "wrote"
        actions.append(rec)
        if limit and len(actions) >= limit:
            break

    if not dry_run and stems:
        ensure_rackup_init(stems)
        patch_bridge(stems)
        entries = []
        for stem in stems:
            entries.append(
                {
                    "id": stem,
                    "name": stem,
                    "source": f"abilities/rackup/{stem}.py",
                    "type": "ability",
                    "status": "CODE",
                    "capabilities": [stem, "rackup"],
                    "modules": [
                        f"abilities/rackup/{stem}.py",
                        f"plugins/rackup_coach/abilities/{stem}.py",
                        "plugins/rackup_coach",
                    ],
                    "secrets_policy": "none — no wallet/key promotion",
                    "note": "Thin wrap from deep_promote_wire",
                }
            )
            catalog_ensure_block(
                stem,
                stem.replace("_", " "),
                [
                    f"abilities/rackup/{stem}.py",
                    f"plugins/rackup_coach/abilities/{stem}.py",
                    "plugins/rackup_coach",
                ],
                f"abilities/rackup/{stem}.py + tools rackup_invoke",
            )
        registry_upsert(entries)
    return actions


def wire_module_abilities(dry_run: bool) -> List[Dict[str, Any]]:
    """Thin wraps for desktop_unique lambdas + agents_advanced."""
    actions = []
    specs = [
        ("desktop_lambda_chat", "modules.desktop_unique.lambda_chat", "abilities/desktop_lambda_chat.py", ["chat", "desktop_unique"]),
        ("desktop_lambda_image", "modules.desktop_unique.lambda_image", "abilities/desktop_lambda_image.py", ["image", "desktop_unique"]),
        ("desktop_lambda_video", "modules.desktop_unique.lambda_video", "abilities/desktop_lambda_video.py", ["video", "desktop_unique"]),
        ("desktop_lambda_advanced", "modules.desktop_unique.lambda_advanced", "abilities/desktop_lambda_advanced.py", ["advanced", "desktop_unique"]),
        ("overmind_runner", "modules.agents_advanced.overmind_runner", "abilities/overmind_runner.py", ["overmind", "agents_advanced"]),
        ("code_engineer_agent", "modules.agents_advanced.code_engineer_agent", "abilities/code_engineer_agent.py", ["code_engineer", "agents_advanced"]),
    ]
    entries = []
    for aid, src, dest_rel, caps in specs:
        # modules.desktop_unique.lambda_chat → modules/desktop_unique/lambda_chat.py
        mod_file = ROOT.joinpath(*src.split(".")).with_suffix(".py")
        if not mod_file.is_file():
            actions.append({"id": aid, "action": "skip_missing_src", "src": str(mod_file)})
            continue
        dest = ROOT / dest_rel
        if dest.is_file():
            actions.append({"id": aid, "action": "skip_exists", "dest": dest_rel})
            continue
        if dry_run:
            actions.append({"id": aid, "action": "would_write", "dest": dest_rel})
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(module_ability_wrap(aid, src, dest_rel, caps), encoding="utf-8")
        actions.append({"id": aid, "action": "wrote", "dest": dest_rel})
        entries.append(
            {
                "id": aid,
                "name": aid,
                "source": dest_rel,
                "type": "ability",
                "status": "CODE",
                "capabilities": caps,
                "modules": [dest_rel, str(mod_file.relative_to(ROOT)).replace("\\", "/")],
                "secrets_policy": "none",
                "note": "Thin wrap from deep_promote_wire (modules → abilities)",
            }
        )
        catalog_ensure_block(
            aid,
            aid.replace("_", " "),
            [dest_rel, str(mod_file.relative_to(ROOT)).replace("\\", "/")],
            dest_rel,
        )
        # bridge alias
        if BRIDGE.is_file():
            text = BRIDGE.read_text(encoding="utf-8")
            needle = f'"{aid}": "abilities.{aid}"'
            # abilities.desktop_lambda_chat — module path is abilities.desktop_lambda_chat for root abilities/
            mod_import = dest_rel.replace("/", ".").removesuffix(".py")
            needle = f'"{aid}": "{mod_import}"'
            if needle not in text:
                marker = '"game_world": "abilities.game_world",'
                if marker in text:
                    text = text.replace(
                        marker,
                        f'            "{aid}": "{mod_import}",\n            ' + marker,
                        1,
                    )
                    BRIDGE.write_text(text, encoding="utf-8")
    if entries and not dry_run:
        registry_upsert(entries)
    return actions


def wire_exportable_orchestrators(dry_run: bool) -> List[Dict[str, Any]]:
    """Do not blind-copy nest orchestrators (relative imports break).

    Instead: README index under modules/orchestrators + thin ability that lists
    scripts/exportable orchestrator_* for patch/adapt.
    """
    actions: List[Dict[str, Any]] = []
    src_dir = ROOT / "scripts" / "exportable"
    dest_dir = ROOT / "modules" / "orchestrators"
    dest_dir.mkdir(parents=True, exist_ok=True)
    names = sorted(p.name for p in src_dir.glob("orchestrator_*.py"))
    readme = dest_dir / "NEST_ORCHESTRATORS.md"
    ability = ROOT / "abilities" / "nest_orchestrators.py"
    body = [
        "# Nest orchestrators (exportable index)",
        "",
        "These modules live under `scripts/exportable/` because they use relative",
        "imports from old package layouts. **Do not blind-copy** into this folder.",
        "",
        "Adapt into `core/orchestration/` or wrap with an explicit import path after review.",
        "",
        "| File | Path |",
        "|------|------|",
    ]
    for n in names:
        body.append(f"| `{n}` | `scripts/exportable/{n}` |")
    body.append("")
    if dry_run:
        actions.append({"id": "nest_orchestrators_readme", "action": "would_write", "dest": str(readme.relative_to(ROOT))})
    else:
        readme.write_text("\n".join(body), encoding="utf-8")
        actions.append({"id": "nest_orchestrators_readme", "action": "wrote", "dest": str(readme.relative_to(ROOT))})

    if not ability.is_file() or not dry_run:
        wrap = '''"""List nest orchestrator salvage under scripts/exportable (thin index ability)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

ABILITY = {
    "id": "nest_orchestrators",
    "name": "nest_orchestrators",
    "type": "ability",
    "status": "CODE",
    "source": "scripts/exportable/orchestrator_*.py",
    "dest": "abilities/nest_orchestrators.py",
    "capabilities": ["nest_orchestrators", "exportable", "promote"],
    "secrets_policy": "none",
}


def run(
    input: str = "",
    context: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    root = Path(__file__).resolve().parents[1]
    exportable = root / "scripts" / "exportable"
    files = sorted(p.name for p in exportable.glob("orchestrator_*.py"))
    return {
        "ok": True,
        "ability": "nest_orchestrators",
        "exportable_dir": str(exportable),
        "orchestrators": files,
        "note": "Relative-import salvage — adapt before promoting into core/orchestration",
        "index_doc": "modules/orchestrators/NEST_ORCHESTRATORS.md",
    }
'''
        if dry_run:
            actions.append({"id": "nest_orchestrators", "action": "would_write", "dest": "abilities/nest_orchestrators.py"})
        else:
            ability.write_text(wrap, encoding="utf-8")
            actions.append({"id": "nest_orchestrators", "action": "wrote", "dest": "abilities/nest_orchestrators.py"})
            registry_upsert(
                [
                    {
                        "id": "nest_orchestrators",
                        "name": "nest_orchestrators",
                        "source": "abilities/nest_orchestrators.py",
                        "type": "ability",
                        "status": "CODE",
                        "capabilities": ["nest_orchestrators", "exportable", "promote"],
                        "modules": [
                            "abilities/nest_orchestrators.py",
                            "scripts/exportable",
                            "modules/orchestrators/NEST_ORCHESTRATORS.md",
                        ],
                        "secrets_policy": "none",
                        "note": "Index of nest orchestrator salvage — adapt before core promote",
                    }
                ]
            )
            if BRIDGE.is_file():
                text = BRIDGE.read_text(encoding="utf-8")
                needle = '"nest_orchestrators": "abilities.nest_orchestrators"'
                if needle not in text:
                    marker = '"game_world": "abilities.game_world",'
                    if marker in text:
                        text = text.replace(
                            marker,
                            f'            {needle},\n            ' + marker,
                            1,
                        )
                        BRIDGE.write_text(text, encoding="utf-8")
    return actions


def rebuild_catalog() -> Optional[str]:
    try:
        from realai.ability_catalog import save_catalog

        p = save_catalog()
        return str(p)
    except Exception as e:
        return f"error:{e}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-rackup", action="store_true")
    ap.add_argument("--skip-modules", action="store_true")
    ap.add_argument("--skip-orchestrators", action="store_true")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    log: Dict[str, Any] = {
        "generated": utc(),
        "dry_run": args.dry_run,
        "queue_exists": QUEUE.is_file(),
        "actions": [],
    }

    if not args.skip_rackup:
        log["rackup"] = wire_rackup(args.dry_run, args.limit)
        log["actions"].extend(log["rackup"])
    if not args.skip_modules:
        log["modules"] = wire_module_abilities(args.dry_run)
        log["actions"].extend(log["modules"])
    if not args.skip_orchestrators:
        log["orchestrators"] = wire_exportable_orchestrators(args.dry_run)
        log["actions"].extend(log["orchestrators"])

    if not args.dry_run:
        log["catalog"] = rebuild_catalog()

    LOG.write_text(json.dumps(log, indent=2), encoding="utf-8")
    wrote = sum(1 for a in log["actions"] if a.get("action") in {"wrote", "copied"})
    would = sum(1 for a in log["actions"] if str(a.get("action", "")).startswith("would"))
    print(
        f"[deep_promote_wire] wrote/copied={wrote} would={would} total_actions={len(log['actions'])} → {LOG}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
