"""Inventory + SHA256 hash delta: product root vs realai package twins.

Writes:
  docs/REALAI_PACKAGE_MAP.md
  docs/REALAI_PKG_CONTENT_DELTA.md

Does NOT park, move, or delete anything.
"""
from __future__ import annotations

import hashlib
import os
import re
from pathlib import Path

ROOT = Path(r"C:\RealAI-clean")
PKG = ROOT / "realai"
DOCS = ROOT / "docs"
SKIP_DIR_NAMES = {
    "node_modules", ".git", "__pycache__", ".pnpm-store", "pnpm-store",
    ".venv", "venv", ".tox", "dist", "build", ".next", ".turbo",
}
INTERESTING_EXT = {".html", ".js", ".css", ".py", ".ts", ".tsx", ".jsx", ".json", ".mjs", ".cjs"}
TWIN_CANDIDATES = {"fusion-ui", "apps", "realai-frontend", "ui", "desktop", "agents-ui", "agents"}
GOLD_NAMES = {
    "orchestration", "learn", "plugins", "catalog", "bot", "cli",
    "_v1_client.py", "__init__.py", "ability_catalog.py", "v3_runtime_bridge.py",
}
GOLD_PREFIXES = ("orchestration", "learn", "plugins", "catalog", "bot", "cli")
NOISE_PATTERNS = [
    re.compile(r".*-default-run$", re.I),
    re.compile(r"^core_unify_", re.I),
    re.compile(r"^pnpm-", re.I),
    re.compile(r".*__dup\d+$", re.I),
    re.compile(r"^\.pytest_cache", re.I),
]


def classify_top(name: str) -> str:
    if name in GOLD_NAMES:
        return "GOLD"
    for pat in NOISE_PATTERNS:
        if pat.match(name):
            return "NOISE"
    if name in TWIN_CANDIDATES:
        return "TWIN"
    # shims: thin wrappers / entrypoints often at package top
    shim_names = {
        "v3_orchestrator.py", "orchestrator.py", "main.py", "__main__.py",
        "_legacy_main.py", "api_server.py", "hive_orchestrator.py",
        "realai_orchestrator.py", "unified_orchestrator.py",
        "realai_hive_orchestrator.py", "realai_local_server.py",
        "nest_orchestrators.py", "router.py", "doctor.py",
    }
    if name in shim_names:
        return "SHIM"
    if name.startswith(".") or name.endswith(".DIR_NOTE.json"):
        return "NOISE"
    return "NOISE" if name in {"__pycache__", ".vs", "Output", "logs", "scan_results"} else "REVIEW_OTHER"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def should_skip_dir(name: str) -> bool:
    return name in SKIP_DIR_NAMES or name.startswith(".pnpm")


def iter_relative_files(base: Path, prefer_roots: list[str], cap: int = 5000):
    """Yield relative posix paths under prefer_roots first, then others."""
    seen = set()
    count = 0
    for root_name in prefer_roots:
        d = base / root_name
        if not d.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(d):
            dirnames[:] = [n for n in dirnames if not should_skip_dir(n)]
            for fn in filenames:
                p = Path(dirpath) / fn
                if p.suffix.lower() not in INTERESTING_EXT:
                    continue
                rel = p.relative_to(base).as_posix()
                if rel not in seen:
                    seen.add(rel)
                    yield rel
                    count += 1
                    if count >= cap:
                        return


def first_unique_symbol(path: Path, max_bytes: int = 8000) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")[:max_bytes]
    except Exception as e:
        return f"(unreadable: {e})"
    # pick a distinctive line
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("//") or s.startswith("#") or s.startswith("/*"):
            continue
        if len(s) > 12:
            return s[:120]
    return "(no symbol)"


def is_gold_rel(rel: str) -> bool:
    parts = rel.replace("\\", "/").split("/")
    if not parts:
        return False
    if parts[0] in GOLD_NAMES or parts[0] in GOLD_PREFIXES:
        return True
    return False


def main() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)

    # --- STEP 1: top-level map ---
    top = sorted([p.name for p in PKG.iterdir()], key=str.lower)
    rows = []
    counts = {"GOLD": 0, "SHIM": 0, "TWIN": 0, "NOISE": 0, "REVIEW_OTHER": 0}
    for name in top:
        cls = classify_top(name)
        counts[cls] = counts.get(cls, 0) + 1
        exists_product = (ROOT / name).exists()
        rows.append((name, cls, "yes" if exists_product else "no"))

    map_md = []
    map_md.append("# RealAI package map (`realai\\` top-level)\n")
    map_md.append("Generated by `scripts/pkg_content_delta.py`. Classification only — no parks.\n")
    map_md.append("\n## Legend\n")
    map_md.append("- **GOLD** — never park (orchestration, learn, plugins, catalog, bot, cli, key py)\n")
    map_md.append("- **SHIM** — entry/shim modules; keep\n")
    map_md.append("- **TWIN** — UI/layout twin candidates vs product root\n")
    map_md.append("- **NOISE** — nest dumps, default-run, caches, pnpm meta\n")
    map_md.append("- **REVIEW_OTHER** — not auto-classified; leave alone\n")
    map_md.append("\n## Counts\n")
    for k in ("GOLD", "SHIM", "TWIN", "NOISE", "REVIEW_OTHER"):
        map_md.append(f"- {k}: {counts.get(k, 0)}\n")
    map_md.append("\n## Table\n")
    map_md.append("| Name | Class | Also at product root? |\n")
    map_md.append("|------|-------|-----------------------|\n")
    for name, cls, ep in rows:
        map_md.append(f"| `{name}` | {cls} | {ep} |\n")
    map_md.append("\n## Served UI (product)\n")
    map_md.append("- `console.html`, `fusion-ui\\`, `agents-ui\\` at product root are served by :8001\n")
    map_md.append("- Package copies under `realai\\` are twin candidates — hash before park\n")
    (DOCS / "REALAI_PACKAGE_MAP.md").write_text("".join(map_md), encoding="utf-8")

    # --- STEP 2: hash pairs ---
    prefer = ["fusion-ui", "apps", "ui", "desktop", "agents", "agents-ui", "realai-frontend"]
    # Collect candidate relatives from package twin dirs
    pkg_rels = list(iter_relative_files(PKG, prefer, cap=4000))

    results = []  # dicts
    identical = diff = unique_pkg = unique_product = 0
    pair_cap = 80

    # Also add product-only interesting under prefer that lack pkg twin? We cap pairs;
    # focus on pkg files that have product counterpart OR note UNIQUE_PKG.
    for rel in pkg_rels:
        if len(results) >= pair_cap:
            break
        pkg_path = PKG / rel
        prod_path = ROOT / rel
        if not pkg_path.is_file():
            continue
        if not prod_path.is_file():
            # UNIQUE_PKG — only count interesting under twin dirs
            unique_pkg += 1
            results.append({
                "rel": rel,
                "cls": "UNIQUE_PKG",
                "pkg_hash": sha256_file(pkg_path)[:16] + "…",
                "prod_hash": "—",
                "pkg_size": pkg_path.stat().st_size,
                "prod_size": 0,
                "note": "only under realai\\",
                "gold": is_gold_rel(rel),
            })
            continue
        ph = sha256_file(pkg_path)
        oh = sha256_file(prod_path)
        psz = pkg_path.stat().st_size
        osz = prod_path.stat().st_size
        if ph == oh:
            identical += 1
            results.append({
                "rel": rel,
                "cls": "IDENTICAL",
                "pkg_hash": ph,
                "prod_hash": oh,
                "pkg_size": psz,
                "prod_size": osz,
                "note": "park candidate",
                "gold": is_gold_rel(rel),
            })
        else:
            diff += 1
            sym = first_unique_symbol(prod_path)
            results.append({
                "rel": rel,
                "cls": "DIFF",
                "pkg_hash": ph,
                "prod_hash": oh,
                "pkg_size": psz,
                "prod_size": osz,
                "note": f"REVIEW; product size={osz} pkg size={psz}; product symbol: `{sym}`",
                "gold": is_gold_rel(rel),
            })

    # Explicit fusion-ui/index.html always first in report
    fui_pkg = PKG / "fusion-ui" / "index.html"
    fui_prod = ROOT / "fusion-ui" / "index.html"
    fui_line = "fusion-ui/index.html: missing"
    if fui_pkg.is_file() and fui_prod.is_file():
        fui_line = (
            f"product={sha256_file(fui_prod)} ({fui_prod.stat().st_size} B); "
            f"pkg={sha256_file(fui_pkg)} ({fui_pkg.stat().st_size} B)"
        )

    # Count UNIQUE_PRODUCT for prefer roots: files at product not in pkg (sample, not exceeding remaining)
    # Only add a few unique product notes for fusion-ui top files missing in pkg
    for root_name in prefer:
        prod_dir = ROOT / root_name
        if not prod_dir.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(prod_dir):
            dirnames[:] = [n for n in dirnames if not should_skip_dir(n)]
            for fn in filenames:
                if Path(fn).suffix.lower() not in INTERESTING_EXT:
                    continue
                p = Path(dirpath) / fn
                rel = p.relative_to(ROOT).as_posix()
                if (PKG / rel).is_file():
                    continue
                # already have this rel? skip
                if any(r["rel"] == rel for r in results):
                    continue
                if len(results) >= pair_cap + 20:  # allow a bit more for UNIQUE_PRODUCT notes
                    break
                unique_product += 1
                results.append({
                    "rel": rel,
                    "cls": "UNIQUE_PRODUCT",
                    "pkg_hash": "—",
                    "prod_hash": sha256_file(p)[:16] + "…",
                    "pkg_size": 0,
                    "prod_size": p.stat().st_size,
                    "note": "KEEP (served / product-only)",
                    "gold": False,
                })
            else:
                continue
            break

    delta = []
    delta.append("# RealAI package vs product content delta\n")
    delta.append("Generated by `scripts/pkg_content_delta.py` **before any quarantine**.\n")
    delta.append("\n## Policy\n")
    delta.append("- **IDENTICAL** → park later (`git mv` to `_quarantine/twins_pkg_ui/`)\n")
    delta.append("- **DIFF** → REVIEW; keep both; do not park; for fusion-ui product wins on :8001\n")
    delta.append("- **UNIQUE_PKG** → REVIEW unless nest dump → NOISE\n")
    delta.append("- **UNIQUE_PRODUCT** → KEEP (served)\n")
    delta.append("- GOLD paths never parked\n")
    delta.append("\n## Counts (this run)\n")
    delta.append(f"- IDENTICAL: {identical}\n")
    delta.append(f"- DIFF: {diff}\n")
    delta.append(f"- UNIQUE_PKG (in capped scan): {unique_pkg}\n")
    delta.append(f"- UNIQUE_PRODUCT (sampled): {unique_product}\n")
    delta.append(f"- Rows recorded: {len(results)} (pair cap {pair_cap} for pkg-driven pairs)\n")
    delta.append(f"\n## fusion-ui/index.html\n\n{fui_line}\n")
    delta.append("\n## Table\n")
    delta.append("| Rel path | Class | Product SHA256 | Package SHA256 | Sizes (prod/pkg) | Note |\n")
    delta.append("|----------|-------|----------------|----------------|------------------|------|\n")
    for r in results:
        ph = r["prod_hash"] if len(r["prod_hash"]) <= 20 else r["prod_hash"]
        kh = r["pkg_hash"] if len(r["pkg_hash"]) <= 20 else r["pkg_hash"]
        # full hashes for IDENTICAL/DIFF
        if r["cls"] in ("IDENTICAL", "DIFF"):
            ph = r["prod_hash"]
            kh = r["pkg_hash"]
        gold_tag = " GOLD" if r.get("gold") else ""
        note = r["note"].replace("|", "/")
        delta.append(
            f"| `{r['rel']}` | {r['cls']}{gold_tag} | `{ph}` | `{kh}` | "
            f"{r['prod_size']}/{r['pkg_size']} | {note} |\n"
        )

    # fusion-ui DIFF note
    delta.append("\n## REVIEW rule notes\n")
    delta.append(
        "- If DIFF on fusion-ui: **served = product**; pkg copy is stale/newer — "
        "do not merge blindly. Package copy stays on disk (no overwrite, no park).\n"
    )
    delta.append("- If DIFF on a .py that is GOLD path, do not park.\n")

    # Park plan summary
    park_dirs = set()
    park_files = []
    for r in results:
        if r["cls"] != "IDENTICAL" or r.get("gold"):
            continue
        # Only park under twin candidate top dirs
        top = r["rel"].split("/")[0]
        if top not in TWIN_CANDIDATES:
            continue
        park_files.append(r["rel"])
        park_dirs.add(top)

    delta.append("\n## Park plan (IDENTICAL twin files only; execute after docs commit)\n")
    if not park_files:
        delta.append("- Zero IDENTICAL twin files in scan → park nothing at file level.\n")
        delta.append(
            "- Directory-level park only if an entire twin dir is byte-identical "
            "(checked separately by runner).\n"
        )
    else:
        delta.append(f"- IDENTICAL parkable files: {len(park_files)}\n")
        for f in park_files[:40]:
            delta.append(f"  - `{f}`\n")
        if len(park_files) > 40:
            delta.append(f"  - … and {len(park_files) - 40} more\n")

    (DOCS / "REALAI_PKG_CONTENT_DELTA.md").write_text("".join(delta), encoding="utf-8")

    # Machine-readable summary for next steps
    summary = ROOT / "scripts" / "_pkg_delta_summary.txt"
    lines = [
        f"IDENTICAL={identical}",
        f"DIFF={diff}",
        f"UNIQUE_PKG={unique_pkg}",
        f"UNIQUE_PRODUCT={unique_product}",
        f"FUSION_UI={fui_line}",
        f"PARK_FILES={len(park_files)}",
        f"PARK_TOPS={','.join(sorted(park_dirs))}",
    ]
    # Also check whole-dir identity for twin tops
    for top in sorted(TWIN_CANDIDATES):
        pkg_d = PKG / top
        prod_d = ROOT / top
        if not pkg_d.is_dir() or not prod_d.is_dir():
            lines.append(f"DIR_{top}=missing_one_side")
            continue
        # hash all interesting files both sides
        def file_map(base: Path):
            m = {}
            for dirpath, dirnames, filenames in os.walk(base):
                dirnames[:] = [n for n in dirnames if not should_skip_dir(n)]
                for fn in filenames:
                    p = Path(dirpath) / fn
                    if p.suffix.lower() not in INTERESTING_EXT and p.suffix.lower() not in {".svg", ".map", ".woff2"}:
                        # still hash all non-skip for dir identity of UI assets
                        if should_skip_dir(p.name):
                            continue
                    rel = p.relative_to(base).as_posix()
                    try:
                        m[rel] = sha256_file(p)
                    except Exception:
                        pass
            return m
        # For dir identity use ALL files except skip dirs
        def all_map(base: Path):
            m = {}
            for dirpath, dirnames, filenames in os.walk(base):
                dirnames[:] = [n for n in dirnames if not should_skip_dir(n)]
                for fn in filenames:
                    p = Path(dirpath) / fn
                    rel = p.relative_to(base).as_posix()
                    try:
                        m[rel] = (sha256_file(p), p.stat().st_size)
                    except Exception as e:
                        m[rel] = (f"ERR:{e}", 0)
            return m
        am = all_map(pkg_d)
        bm = all_map(prod_d)
        if set(am.keys()) != set(bm.keys()):
            only_pkg = len(set(am) - set(bm))
            only_prod = len(set(bm) - set(am))
            lines.append(f"DIR_{top}=DIFF_TREE only_pkg={only_pkg} only_prod={only_prod} shared={len(set(am)&set(bm))}")
        else:
            mism = [k for k in am if am[k][0] != bm[k][0]]
            if not mism:
                lines.append(f"DIR_{top}=IDENTICAL files={len(am)}")
            else:
                lines.append(f"DIR_{top}=DIFF_CONTENT mismatches={len(mism)} files={len(am)}")

    summary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print("WROTE", DOCS / "REALAI_PACKAGE_MAP.md")
    print("WROTE", DOCS / "REALAI_PKG_CONTENT_DELTA.md")


if __name__ == "__main__":
    main()

